version: '3.7'
services:
  api:
    build:
      context: ./airai-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .api.env
  web:
    build:
      context: ./airai-web
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - api
    env_file:
      - .web.env